[project]
name = "nagoya-bus-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "botocore[crt]>=1.41.1",
    "pandas>=2.3.3",
    "strands-agents>=1.17.0",
]
